language: ruby
rvm:
- 1.9.3
script: bundle exec rake travis
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: X4sgmJQxijjyLodMkj9gt0gqQxPgGXWqIqv4Hz/lk0SNBmWyXsO4LuxFi3clIXTH/qaDVkmslDSN7L5iExIRXK7WkMHKIptWF7ANiefFX4A+QaENteFsqEp1bLteRramklmOeQ8BxaHCuKf06jsm7IN9ZVCIo1E9hBQxKi/Ympq5LqToPp5pfL3/TUzkGRWtOoLa0DxZhSC8VS+rw770S2uzh4Nb+qg1sT6pP1Tk0dRtZ+v97l/eUmJTUjYphrCsj3rLe04n3dIqSfpl/WORNMEBM4Q5iNShCjZHX//Elqg0TUYJtp3zhumoB7IZ0xwflGi9TW4eoOcd+31yItMJGSYm476NTUO0hPtIONczijaQS5Dv6KQXi9RKb12PytMOd17WZdNu9M9dbTin4HKxIlKWwzyIdE4yALSX4F/7cR7H8zkDHCvdjSbUTCX+JeTiz1foS44bh9Kc7AHgrWsc2wcJ9JlYYFeFzK4NeIVp18I40wzgBr9VE94BN8UZzcCrDCSjYJMf3b9+FhcEG5wxwVVGe7nxXCYGWtrTe5B+WN79EjYfy8Zv2DUsmj09YcMpg1RrdRaw7n93fx3BPjigfwoQC2UUoUaCtUYz8VNfV9Alni/Qmh8HjcDsJS235ILBR4dY0up2BTwsAp2u0cf+je5oLcjZd/xDa11WqqR8S6M=
install:
- git config --global user.email "davidnaffis@gmail.com"
- git config --global user.name "naffis"